// Generated by Haxe 4.0.0 (git build development @ 3018ab109)
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace format.tools {
	public class Deflate : global::haxe.lang.HxObject {
		
		public Deflate(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Deflate() {
			global::format.tools.Deflate.__hx_ctor_format_tools_Deflate(this);
		}
		
		
		protected static void __hx_ctor_format_tools_Deflate(global::format.tools.Deflate __hx_this) {
		}
		
		
		public static global::haxe.io.Bytes run(global::haxe.io.Bytes b, global::haxe.lang.Null<int> level) {
			unchecked {
				global::haxe.lang.Null<int> level1 = ( ( ! (level.hasValue) ) ? (new global::haxe.lang.Null<int>(9, true)) : (level) );
				return global::haxe.zip.Compress.run(b, (level1).@value);
			}
		}
		
		
	}
}


