// Generated by Haxe 4.0.0 (git build development @ 3018ab109)
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.zip {
	public class Compress : global::haxe.lang.HxObject {
		
		public Compress(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Compress() {
			global::haxe.zip.Compress.__hx_ctor_haxe_zip_Compress(this);
		}
		
		
		protected static void __hx_ctor_haxe_zip_Compress(global::haxe.zip.Compress __hx_this) {
		}
		
		
		public static global::haxe.io.Bytes run(global::haxe.io.Bytes s, int level) {
			throw global::haxe.lang.HaxeException.wrap("Not implemented for this platform");
		}
		
		
	}
}


