// Generated by Haxe 4.0.0 (git build development @ 3018ab109)
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.root {
	public class Math {
		
		public Math() {
		}
		
		
		public static int round(double v) {
			unchecked {
				int vint = ((int) (v) );
				double dec = ( v - vint );
				if (( ( dec >= 1 ) || ( dec <= -1 ) )) {
					return vint;
				}
				
				if (( dec >= .5 )) {
					return ( vint + 1 );
				}
				
				if (( dec < -.5 )) {
					return ( vint - 1 );
				}
				
				return vint;
			}
		}
		
		
	}
}


