// Generated by Haxe 4.0.0 (git build development @ 3018ab109)

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.io {
	public class ArrayBufferViewImpl : global::haxe.lang.HxObject {
		
		public ArrayBufferViewImpl(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ArrayBufferViewImpl() {
			global::haxe.io.ArrayBufferViewImpl.__hx_ctor_haxe_io_ArrayBufferViewImpl(this);
		}
		
		
		protected static void __hx_ctor_haxe_io_ArrayBufferViewImpl(global::haxe.io.ArrayBufferViewImpl __hx_this) {
		}
		
		
	}
}


